Fix ListCommand::execute() must be of the type int
Fatal error: Uncaught TypeError: Return value of "DigipolisGent\Github\Core\Command\Repo\ListCommand::execute()" must be of the type int, "null" returned. in /Volumes/webdev/www/digipolis/php_scripts_github/vendor/symfony/console/Command/Command.php on line 301

TypeError: Return value of "DigipolisGent\Github\Core\Command\Repo\ListCommand::execute()" must be of the type int, "null" returned. in /Volumes/webdev/www/digipolis/php_scripts_github/vendor/symfony/console/Command/Command.php on line 301

Call Stack:
    0.0022     394120   1. {main}() /Volumes/webdev/www/digipolis/php_scripts_github/bin/github:0
    0.0041     405088   2. require('/Volumes/webdev/www/digipolis/php_scripts_github/bin/github.php') /Volumes/webdev/www/digipolis/php_scripts_github/bin/github:5
    0.0488    2490440   3. DigipolisGent\Github\Application->run() /Volumes/webdev/www/digipolis/php_scripts_github/bin/github.php:49
    0.0749    2838504   4. DigipolisGent\Github\Application->doRun() /Volumes/webdev/www/digipolis/php_scripts_github/vendor/symfony/console/Application.php:171
    0.0776    2852360   5. DigipolisGent\Github\Application->doRunCommand() /Volumes/webdev/www/digipolis/php_scripts_github/vendor/symfony/console/Application.php:299
    0.0776    2852360   6. DigipolisGent\Github\Core\Command\Repo\ListCommand->run() /Volumes/webdev/www/digipolis/php_scripts_github/vendor/symfony/console/Application.php:1005